version: "3.9"

services:

  order:
    container_name: order
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@order_postgres:5432/order
    depends_on:
      - order_postgres
    volumes:
      - ./migrations:/app/migrations

  order_postgres:
    container_name: order_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=order
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data